### ISSUE TITLE
World making

### ISSUE THREAD

**Issue by Builder2007** [MultiCraft/MultiCraft_game#68] opened 2021-05-23 10:18 UTC
When i try and make a world it doesnt let me and starts saying error and it happens to my dad as well

**Comment by MoNTE48** [comment] 2021-05-23 10:48
Hello.
I can't help because there are no details about the error here at all. No app name, no your OS version( Android, iOS, Mac), etc.

**Comment by Builder2007** [comment] 2021-05-23 11:39
This is what it says
![Uploading 6518D291-110C-4BD7-95FA-453CCF0F2A33.png…]()

**Comment by Builder2007** [comment] 2021-05-23 11:40
![5376F6E7-B0C2-45A3-97D8-F74533203F85](https://user-images.githubusercontent.com/84663669/119259013-1bd72200-bbc4-11eb-8eec-d74f521f7a58.png)

**Comment by MoNTE48** [comment] 2021-05-23 11:49
Android? iOS? macOS?

**Comment by MoNTE48** [comment] 2021-05-23 15:18
Bug confirmed and will be fixed in next update.
Thanks for report.

**Comment by YaurelTV** [comment] 2021-05-27 05:17
Como puedo crear un servidor en Multicraft IOS?

**Closed** 2021-09-03 17:29 UTC
