### ISSUE TITLE
Entering servers

### ISSUE THREAD

**Issue by Multicraftbuilder2007** [MultiCraft/MultiCraft_game#63] opened 2021-04-09 16:57 UTC
When i try and enter any server it says i cannot connect to severs it happens to all my family that has it

**Comment by JADERZZZ** [comment] 2021-04-12 05:37
Did you just restart yung phone?
So it can be restart

**Comment by noahplayer** [comment] 2021-04-29 20:57
Yeah I can’t join public servers either

**Comment by MoNTE48** [comment] 2021-04-30 19:22
Most of the public servers are hosted by other people who are not affiliated with us in any way. If you really can't connect to them, the problem is clearly on your side.
This is a repository for developing a single player version of the game, so I am closing this Issue.

**Closed by MoNTE48** 2021-04-30 19:22 UTC
