### ISSUE TITLE
Server exists, not turned on, not recognised as owner

### ISSUE THREAD

**Issue by pmatthews05** [MultiCraft/MultiCraft_game#56] opened 2021-02-12 17:49 UTC
Hi, my kids play your game on their iPads.

They had to remove the app and add it back onto their iPad, but now they are unable to start and log into the server.

They have the code, username and password. It either states that the server exists but not turned on, and ask the owner to turn it on. One of them is the owner, but it’s just not letting them start the server or log in.

Can you help?

**Comment by MoNTE48** [comment] 2021-02-19 21:29
Hello. Please, use Recover Server tab for restoring assets to server after reinstall on changing device. Thanks

**Comment by pmatthews05** [comment] 2021-02-20 18:02
Tried that, we put username and password clicked recover and it stated “invalid username or password”. Then we tried the other side with the code, admin and password, but that states “invalid invite code, username or password”. 

Definitely right details that is being put in.

**Comment by MoNTE48** [comment] 2021-03-03 11:21
At the moment, there is no way to reset your password, and if you forget it, you irrevocably lost access to the server.
It is the player's responsibility to write down and securely store the password.
I am closing this because it is not a bug.

**Closed by MoNTE48** 2021-03-03 11:21 UTC
